KCFinder_browse:
  path: /kcfinder/{file}
  controller: Ikadoc\KCFinderBundle\Controller\ProxyController::proxyAction
  requirements:
    file: "favicon\\.ico|browse\\.php|js_localize\\.php|upload\\.php|css/index\\.php|js/index\\.php|themes/[^\\.]*/css\\.php|themes/[^\\.]*/js\\.php|themes/[^\\.]*/img/[^\\.]*\\.(png|gif|jpg)"
